"""
Assemble everything the page needs into one JSON payload, then render the page.

Run:
    python3 build.py            # uses the committed CSVs
    python3 build.py --fetch    # refreshes market data first

Writes:
    market.json     per-asset monthly returns and the model definitions
    survival.json   the endgame grid from the paper's block bootstrap
    game.json       the whole payload, market plus client plus decisions
    index.html      the page, self-contained and offline
    artifact_body.html   the same page as a body fragment, for publishing
    transcript.md   every decision and every option, readable on a phone
"""

import json
import os
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
sys.path.insert(0, HERE)

import client  # noqa: E402
import decisions as DEC  # noqa: E402
import market  # noqa: E402
import survival  # noqa: E402


# The three paths the debrief compares a player against. Each is a complete set
# of choices, run through the same engine as the player's own, so the comparison
# is like for like rather than a remembered number.
COMPARISONS = {
    "left_alone": {
        "label": "Left alone",
        "blurb": "The questionnaire answer, taken at face value and never "
                 "revisited. Cautious from the start, no glidepath, no cash "
                 "reserve, every review a formality.",
        "picks": {"d01_open": "b", "d02_gift": "a", "d03_peak": "a",
                  "d04_call": "b", "d05_bottom": "b", "d06_retire": "a",
                  "d07_taper": "a", "d08_grandchildren": "a", "d09_fee": "a",
                  "d10_covid": "a", "d11_duration": "a", "d12_letter": "a",
                  "d13_concentration": "a"},
    },
    "instinct": {
        "label": "Her instincts",
        "blurb": "What Ruth would have done on her own. Safety first, cash "
                 "whenever it is frightening, and back in once it feels calm "
                 "again.",
        "picks": {"d01_open": "a", "d02_gift": "a", "d03_peak": "c",
                  "d04_call": "a", "d05_bottom": "d", "d06_retire": "c",
                  "d07_taper": "c", "d08_grandchildren": "a", "d09_fee": "a",
                  "d10_covid": "c", "d11_duration": "c", "d12_letter": "d",
                  "d13_concentration": "a"},
    },
    "by_the_book": {
        "label": "By the book",
        "blurb": "Every decision made the way the file would want it made: "
                 "documented, tied to her circumstances rather than to a "
                 "forecast, and boring on purpose.",
        "picks": {"d01_open": "c", "d02_gift": "b", "d03_peak": "b",
                  "d04_call": "c", "d05_bottom": "a", "d06_retire": "b",
                  "d07_taper": "a", "d08_grandchildren": "c", "d09_fee": "b",
                  "d10_covid": "b", "d11_duration": "b", "d12_letter": "b",
                  "d13_concentration": "b"},
    },
}


def client_payload():
    bands = [{"from": f, "to": t, "min": lo, "max": hi, "why": why}
             for f, t, lo, hi, why in client.SUITABILITY_BANDS]
    return {
        "name": client.NAME,
        "born": client.BORN,
        "birth_month": client.BIRTH_MONTH,
        "pot": client.POT,
        "income": client.INCOME,
        "income_from": client.INCOME_FROM,
        "inflation": client.INFLATION,
        "fee": client.FEE,
        "start_month": client.START_MONTH,
        "end_month": client.END_MONTH,
        "dies_at": client.DIES_AT,
        "age_at_end": client.AGE_AT_END,
        "profile": client.PROFILE,
        "intro": client.INTRO,
        "bands": bands,
    }


def build_payload():
    market_payload, _, _ = market.build()
    survival_payload = survival.build()
    return {
        "market": market_payload,
        "survival": survival_payload,
        "client": client_payload(),
        "decisions": DEC.DECISIONS,
        "brief": DEC.BRIEF,
        "comparisons": COMPARISONS,
    }


def write_transcript(payload, path):
    """A plain-text version of the whole script.

    The page cannot be opened from a phone browsing a private repository, so the
    entire decision script is also written out as markdown that GitHub will
    render. Every option and every consequence is here, which also makes the
    writing easy to review and argue with without running anything.
    """
    L = []
    c = payload["client"]
    L.append("# The Manager's Seat: full transcript\n")
    L.append("Every decision point and every option, including the ones a "
             "player will not see because they depend on earlier choices. "
             "Generated by `build.py`, so it cannot drift out of step with the "
             "page.\n")
    L.append(f"**{c['name']}**, born {c['born']}. £{c['pot']:,} at "
             f"{c['start_month']}, income of £{c['income']:,} a year in 2004 "
             f"money from {c['income_from']}, uprated at "
             f"{c['inflation']*100:.1f}% a year. All-in charge "
             f"{c['fee']*100:.2f}% a year at the start.\n")
    L.append("---\n")

    for i, d in enumerate(payload["decisions"], 1):
        L.append(f"## {i}. {d['title']}")
        L.append(f"*{d['month']}, she is {d['age']}*\n")
        for para in d["context"]:
            L.append(f"{para}\n")
        if d.get("client"):
            L.append(f"> {d['client']}\n")
        L.append(f"**{d['question']}**\n")
        for o in d["options"]:
            L.append(f"### {o['id'].upper()}. {o['label']}")
            if o.get("detail"):
                L.append(f"{o['detail']}\n")
            bits = []
            if o.get("model"):
                bits.append(f"model: {payload['market']['labels'][o['model']]}")
            if o.get("reserve_years"):
                bits.append(f"cash reserve: {o['reserve_years']:g} years")
            if o.get("one_off"):
                bits.append(f"cash movement: £{o['one_off']:,}")
            if o.get("fee") is not None:
                bits.append(f"charge: {o['fee']*100:.2f}%")
            if o.get("withdrawal"):
                bits.append(f"income basis: {o['withdrawal']}")
            if o.get("suspend_months"):
                bits.append(f"income suspended: {o['suspend_months']} months")
            if o.get("requires"):
                bits.append("only offered if the earlier choices allow it")
            bits.append(f"suitability {o['suitability']:+d}")
            bits.append(f"conduct {o['conduct']:+d}")
            L.append("*" + ", ".join(bits) + "*\n")
            if o.get("file"):
                L.append(f"File note: {o['file']}\n")
            L.append(f"{o['after']}\n")
        L.append("---\n")

    with open(path, "w") as f:
        f.write("\n".join(L))


def main():
    if "--fetch" in sys.argv:
        print("refreshing market data")
        subprocess.check_call([sys.executable, "fetch_data.py"],
                              cwd=os.path.join(HERE, "..", "analysis"))
        subprocess.check_call([sys.executable, "fetch_extra.py"], cwd=HERE)

    payload = build_payload()

    with open(os.path.join(HERE, "market.json"), "w") as f:
        json.dump(payload["market"], f, separators=(",", ":"))
    with open(os.path.join(HERE, "survival.json"), "w") as f:
        json.dump(payload["survival"], f, separators=(",", ":"))
    with open(os.path.join(HERE, "game.json"), "w") as f:
        json.dump(payload, f, separators=(",", ":"))

    write_transcript(payload, os.path.join(HERE, "transcript.md"))

    size = os.path.getsize(os.path.join(HERE, "game.json")) / 1024
    print(f"game.json: {size:.0f} KB, {len(payload['decisions'])} decisions, "
          f"{len(payload['market']['months'])} months")

    import render
    render.main()


if __name__ == "__main__":
    main()
